add Vietnam region & Sea route (constants.go)
KnutZuidema/golio pull request #55
Opened 2023-07-18 06:46 UTC by nggialac

2023-07-18 13:44 UTC, KnutZuidema requested changes
Thanks for the contribution! Looks fine to me, just please adjust the names.

2023-07-18 13:44 UTC, KnutZuidema commented on api/constants.go
> +	RouteSea      Route = "sea"
```suggestion
	RouteSEA      Route = "sea"
```

SEA is an acronym on this case (South-East Asia).

2023-07-18 13:44 UTC, KnutZuidema commented on api/constants.go
> +	RegionVietNam           Region = "vn2"
```suggestion
	RegionVietnam           Region = "vn2"
```

2023-07-19 05:15 UTC, nggialac commented
I think that is ok, glad to this useful

2023-07-19 14:09 UTC, KnutZuidema approved these changes
Thank you!

2023-07-19 15:24 UTC, merged